apiVersion: v1
items:
- apiVersion: v1
  data:
    APPDYNAMICS_AGENT_ACCOUNT_NAME: customer1
    APPDYNAMICS_CONTROLLER_HOST_NAME: 172.26.42.50
    APPDYNAMICS_CONTROLLER_PORT: "8090"
    APPDYNAMICS_CONTROLLER_SSL_ENABLED: "false"
    APPDYNAMICS_NETVIZ_AGENT_PORT: "3892"
  kind: ConfigMap
  metadata:
    name: warden-config
- apiVersion: v1
  data:
    JAVA_OPTS: -Dappdynamics.controller.ssl.enabled=$(APPDYNAMICS_CONTROLLER_SSL_ENABLED)
      -Dappdynamics.agent.accountName=$(APPDYNAMICS_AGENT_ACCOUNT_NAME) -Dappdynamics.agent.applicationName=$(APPDYNAMICS_AGENT_APPLICATION_NAME)
      -Dappdynamics.agent.tierName=$(APPDYNAMICS_AGENT_TIER_NAME) -Dappdynamics.agent.reuse.nodeName=true
      -Dappdynamics.agent.reuse.nodeName.prefix=$(APPDYNAMICS_AGENT_REUSE_NODE_NAME_PREFIX)
      -javaagent:/opt/appdynamics/javaagent.jar
  kind: ConfigMap
  metadata:
    name: warden-java-opts-config
- apiVersion: v1
  data:
    AppDynamicsConfig.json: "{\r\n    \"feature\": [\r\n        \"FULL_AGENT\"\r\n
      \   ],\r\n    \"log\": [\r\n        {\r\n        \"outputtype\": \"console\"\r\n
      \       }\r\n    ]\r\n}"
  kind: ConfigMap
  metadata:
    name: appd-config
kind: List
