---
apiVersion: v1
kind: Namespace
metadata:
   name: mutation
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mutation
  name: warden-deployment
  labels:
    app: warden
spec:
  replicas: 3
  selector:
    matchLabels:
      app: warden
  template:
    metadata:
      labels:
        app: warden
    spec:
      containers:
      - name: warden
        image: repo.isw.la/appd-webhook:1.0
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: warden
  namespace: mutation
spec:
  selector:
    app: warden
  ports:
  - port: 443
    targetPort: 5000
